name: BlueMapPlayerModelsPaper
version: 0.4.0
main: dev.kacboy.bluemapplayermodels.BlueMapPlayerModelsPlugin
api-version: '26.2'
depend: [BlueMap]
authors: [kacboy]
description: Adds simple skin-textured 3D live player models to BlueMap 5.23.
